### ISSUE TITLE
Adding placeholders inside html tags inside translations

### ISSUE THREAD

**Issue by khrynczenko** [andreasewering/travelm-agency#136]
Let's say I want to specify a placeholder for a link that would use inside an html tag like this `<a href={link}>Some text </a>` which is inside a translation. So inside a translation `.json` file it would look something like this.

```json 
"linkTranslationId": "Some text <a href={link}>Link text</a> and the rest" ,
```
Right now this produces an error when calling `travelm-agency` like the one below.
```bash
Failed to parse translation file: Expecting \" at row:41 col:166
	Context:
		- fileExtension: json
		- language: en
		- translationFileName: translationfile
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```
What we would expect the generated code to be would look something like this.
```elm
es : I18n
es = {
    linkTranslationId_ =
        \link aAttrs ->
            [ Html.text "Some text "
            , Html.node
                "a"
                ([ Html.Attributes.attribute "href" link
                 ]
                    ++ aAttrs
                )
                [ Html.text "Link text" ]
            , Html.text "and the rest"
            ]
}
```

What do you think? Maybe there is some other way to do it already which we don't know about? If you need some clarification please let me know.

**Comment by andreasewering** [comment]
Hi Krzysztof,
right now the parser does not understand interpolations inside of attributes, but I should be able to make it work.
I'd implement it in a way that the double quotes are necessary though.

```
"linkTranslationId": "Some text <a href="{link}">Link text</a> and the rest" ,
```
(note {link} is wrapped in double quotes)

My reason for that is that it gives you more flexibility:
```
<a description=some prefix {restOfDescription} something else nextAttribute={test}></a>
<a description="some prefix {restOfDescription} something else" nextAttribute="{test}"></a>
```
In the former case, the parser cannot know when the `description` attribute ended and when the next attribute begins, with the double quotes, it can.

I'll let you know when I implemented this (expect about a week).

**Comment by andreasewering** [comment]
Should work in the latest version (3.2.0).
Interestingly, the fluent parser already supported this feature (with the fluent interpolation syntax `{ $varName }`).

Feel free to reopen if it does not work as expected for you.
