### ISSUE TITLE
CLI prints "Compiled in DEV mode"

### ISSUE THREAD

**Issue by megapctr** [andreasewering/travelm-agency#19]
It seems the CLI was compiled without `--optimize`, as it keeps printing about DEV mode. It is a little bit annoying to see this line every time I'm using the CLI.

```
travelm-agency --version
Compiled in DEV mode. Follow the advice at https://elm-lang.org/0.19.1/optimize for better performance and smaller assets.
2.3.1
```

**Comment by andreasewering** [comment]
I must have forgotten to add in the optimize flag after using Elms Debug module during development. Should be fixed in version 2.3.2. Thanks for noticing :)
