### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by janwirth** [andreasewering/travelm-agency#4]
Great work

Things that could be added to the docs
- recording of tool in action using asciinema, this helps people understand what is happening by example.
- comparison / compatibility with fluent
- make naming consistent elm-i18n -> travelm agency. Travelm-agency ist the more unique name
- get the package submitted to the catalog by alex korban

**Comment by andreasewering** [comment]
Thanks for your suggestions!

- Recording to provide an example is a great idea, will do.
- I did not know fluent existed, I'll check it out. At first glance it provides some advanced features such as singular/plural, which should be possible to add here as well.
- Yeah the naming is a good point, I'll rename it to travelm-agency. I noticed too late that I need a unique name for npm.
- I'll contact Alex when I implemented your other suggestions :)

**Comment by andreasewering** [comment]
Done, kind of. I built a Fluent Parser which can parse pretty much all the simple constructs the language has to offer.
How to implement the pattern matching like syntax for things like singular/plural is not clear to me.

Should I generate ports for a pseudo-synchronous communication with the Intl browser API? Is there another option?

**Comment by janwirth** [comment]
https://github.com/wolfadex/fluent-web - here they are using custom elements. However it is possible to get synchronous interop with JS in elm when injecting a proxy as a JSON value. It will still need decoding though. Maybe that's possible in an earlier step? I invited you to an example: https://github.com/janwirth/elm-sync-js-interop/invitations.

**Comment by andreasewering** [comment]
Oh wow that is very interesting. Seems dependent on the way the Elm Compiler works but results in a pretty nice synchronous API! I'll give wrapping the Intl API with a proxy a try.

**Comment by andreasewering** [comment]
It works well for things like Pluralization, where you only need 2 levels of proxies: one for the language and one for the number. In complex scenarios such as number formatting with optional arguments, we need something more advanced. 
I think serializing to JSON should work well. So in Elm you could decode the field "{ style: 'currency', currency: 'JPY' }" which the JS Proxy then deserializes via JSON.parse.

**Comment by janwirth** [comment]
Yes that's exactly the way I would do it too.

**Comment by andreasewering** [comment]
I implemented code generation for the NUMBER and DATETIME functions, I think matching on PluralRules should be the last missing feature for Fluent compatability :)

**Comment by andreasewering** [comment]
Done! String and Number Matching is working now. There are some details like PluralRules options that are not passed yet but I will close this ticket now. Feel free to open a new ticket for improvements if needed.

**Comment by janwirth** [comment]
Thank you!
